$ANSIBLE_VAULT;1.1;AES256
34626565323363643433663862313630643434386634643966353735653331383962353039336539
3830373130343733366462303230323036373166303034390a643734316265303130663832643431
62633633316363333835393334643935613237333837663132656339313630363430316264303331
6237363065393565380a646230643737343135343131393433336132363430323036363232613430
62653662316563376661336132353837323831336636386331383561656331313937646436373835
32323764613632623030393535383132663330343034366434623137643333623365616636346463
32383565366663343331333632323431353639393335363132393335343339336234343865343462
65663734343138393063396365333131623065653638333862343763346261376234623838313032
39393163393866633639623436376331616637376236633462313631373735663035323538633536
3665383436613362356163626137353435373539633337376539
