dns_aws_access_key_id: "{{ vault_dns_aws_access_key_id }}"
dns_aws_secret_access_key: "{{ vault_dns_aws_secret_access_key }}"
dns_record_sets:
  - record: proxmox.kijowski.casa
    value: "192.168.50.3"
  - record: truenas.kijowski.casa
    value: "192.168.50.4"
  - record: "*.k8s.kijowski.casa"
    value: "192.168.50.7"
  - record: "files.kijowski.casa"
    value: "192.168.50.12"
  - record: "arm.kijowski.casa"
    value: "192.168.50.13"
  - record: homebridge.kijowski.casa
    value: "192.168.50.15"
