$ANSIBLE_VAULT;1.1;AES256
37646666366661653261623833323039663062376634346561646266326635633565626334363535
3234376263636366363836663835313637333861643462660a353834333262633636616339623664
36623332636634383962393038366336353936363237646637356134343362303865313534383766
3437346362613434640a313030376135373831383464366233346234333532636563663733323134
30303832613635313332616361376539373639393236336332633962633061623065393763386639
30643331343038363939333866346534306565336231363663323036366435623737623864383135
64383064316664373965383964313034326339383232646136306132626439303965356132323130
63303639656165633536656565633966386138646139353161666336326132646335356533353531
32346436616338323537623039643436613462373732616338303533386239316364353136373431
35626533656561343032363539623634343765366133663762633834326461663531376662393565
30313439313261623966633465613233373664643436336432633332333732343533383435653835
37323337633539636338333462393466663538356435666235366261386462666639393934393534
36343132663162663033653630353934303466396338386638376666613665336232643932633431
37363863653635646665613864323438346164623232653766656365313561326466373032643838
64303830626364306533383734613664656532316231336164643066393438666431393839613039
39396266376464316330643037376566353663623534626137353661333132373638396134656537
3763
