aws_access_key_id: "{{ vault_aws_access_key_id }}"
aws_secret_access_key: "{{ vault_aws_secret_access_key }}"
aws_hosted_zone_id: "{{ vault_aws_hosted_zone_id }}"

traefik_group_id: 1500
traefik_group_name: traefik

traefik_user_id: 1500
traefik_user_name: traefik

traefik_container_image: "docker.io/traefik"
traefik_container_tag: "v3.2"
traefik_container_name: traefik

traefik_acme_email: agkijow@gmail.com
