traefik_group_id: 1500
traefik_group_name: traefik

traefik_user_id: 1500
traefik_user_name: traefik

traefik_container_image: "docker.io/traefik"
traefik_container_tag: "v3.2"
traefik_container_name: traefik
