$ANSIBLE_VAULT;1.1;AES256
65633063313765646562396464376562346364363161333138383234623663333931646661666539
6632623134616234666332633866616161303761353866350a616266623337326635613635373134
35383632306539623161396138376633363163633266306235323338326237663164383731633933
6161666335386462350a646338663863386437663632353162353431316265393861663239306334
31373566326561346261626363363830363237666565333862663337376339663434363735393438
37313431663866343262303036366632323637633931373037326162363237363464653838313035
64346635356433386366353861306236353638633463653935633163313836666463646530663466
39396235633264313661323962616266646230663139323965646636313538356264393137343334
33313761376565376139383337383963666236646434666631346562306334316333306331366163
31396361656232346331373838353963346531333835383832653134653934363430643766393030
38303132646265663736333239633334313166343935613538626538363931656235333036306430
65376661363335613536346238646335333732623636306365313062633337316230376564643130
3339
