---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: database
  namespace: argocd
  # Finalizer that ensures that project is not deleted until it is not referenced by any application
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: Database CRDs and Applications
  sourceRepos:
    - '*'
  destinations:
    - namespace: 'database'
      server: https://k8s.kijowski.casa:6443
    - namespace: 'database-crds'
      server: https://k8s.kijowski.casa:6443
    - namespace: 'database'
      server: https://kubernetes.default.svc
    - namespace: 'database-crds'
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
