---
- import_tasks: preflight.yml
  tags:
    - adguard_install
    - adguard_update

- import_tasks: install.yml
  become: true
  tags:
    - adguard_install

- import_tasks: update.yml
  become: true
  tags:
    - adguard_update
