apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd
resources:
  - base/argocd-namespace.yaml
  - base/traefik-ingressroute.yaml
  - https://raw.githubusercontent.com/argoproj/argo-cd/v2.7.2/manifests/install.yaml

patches:
  - path: overlays/production/argocd-cmd-params-cm.yaml
