# K3s cluster vars
k3s_release_version: stable
k3s_become: true
# https://github.com/PyratLabs/ansible-role-k3s/blob/main/README.md#important-note-about-k3s_install_hard_links
# converting symbolic links to hard links: https://superuser.com/a/560610
k3s_install_hard_links: true
