$ANSIBLE_VAULT;1.1;AES256
38393764316265396538393265613935386163346162363839653036616530623865376338366431
6462663535373833316139656131643134336239666165380a376261323936356136393236646336
36666464656364346635636136373531323032386163646538336332316239316531363737343430
3737653262653131310a643534393336386664346634383964616264303833653532383566633763
33616633383330333337396362336437646362613131346164323263366465663263363266636430
38623837393566613362386232303463366136336262633064653063633863353332326565656462
65663734353564356533663936663130613331313637616264643162323462383362386266343537
37616164643837646433636431366539666464613636316362346361633435613131613664316333
39626165326530613935663062313335383464633239666130626264393866643331663665333136
37323532636363356163323538363766373938643934663861646238376363623361663462303634
32313237353537316639326436356338656632393664336335346266646562366365303932633437
36626463656461643038363139323261626163613735663764353861366666646466383330393665
6164
