---
# https://docs.ansible.com/ansible/latest/reference_appendices/general_precedence.html
# use -e 'ansible_user=root' to override the default user set in inventory vars
- name: Ensure default users exist
  hosts:
    - proxmox_nodes
  become: true
  tags:
    - init
    - users
  vars:
    users:
      - name: ansible
        system: true
        comment: Ansible automation user
      - name: admin
        system: false
        comment: Admin user
  tasks:
    - name: Install sudo from apt
      ansible.builtin.apt:
        cache_valid_time: 86400 # 1 day
        name: sudo
        state: latest

    - name: Create Default Groups
      ansible.builtin.group:
        name: "{{ item.name }}"
        system: "{{ item.system }}"
        state: present
      loop: "{{ users }}"
      loop_control:
        label: "{{ item.name }}"

    - name: Create Default Users
      ansible.builtin.user:
        name: "{{ item.name }}"
        group: "{{ item.name }}"
        create_home: true
        shell: /bin/bash
        comment: "{{ item.comment }}"
        system: "{{ item.system }}"
        state: present
      loop: "{{ users }}"
      loop_control:
        label: "{{ item.name }}"

    - name: Allow Ansible group to have passwordless sudo
      ansible.builtin.copy:
        content: "%ansible ALL=(ALL:ALL) NOPASSWD:ALL"
        dest: /etc/sudoers.d/ansible
        mode: '0440'
        validate: '/usr/sbin/visudo -cf %s'

    - name: Add SSH key
      ansible.posix.authorized_key:
        user: "{{ item }}"
        state: present
        key: 'https://github.com/akijowski.keys'
      loop:
        - ansible
        - admin

# Note: Proxmox automatically updates packages on a schedule. This may not be necessary
- name: Update APT packages
  hosts:
    - proxmox_nodes
  become: true
  tags:
    - init
    - packages
  tasks:
    - name: Update packages
      ansible.builtin.apt:
        upgrade: true
        update_cache: true
        autoclean: true
        autoremove: true
        cache_valid_time: 86400 # 1 day
        state: present
      register: upgrade
      retries: 30 # 10 minutes
      delay: 20
      until: upgrade is success

- name: Ensure base packages
  hosts:
    - proxmox_nodes
  become: true
  tags:
    - init
    - base
  tasks:
    - name: Update packages
      ansible.builtin.apt:
        upgrade: true
        state: present
      register: upgrade
      retries: 30 # 10 minutes
      delay: 20
      until: upgrade is success

    - name: Install base packages
      ansible.builtin.apt:
        update_cache: true
        autoclean: true
        autoremove: true
        cache_valid_time: 86400 # 1 day
        name: "{{ apt_default_packages }}"
        state: latest

# - name: Ensure base configuration
# download helper scripts
# run helper scripts
