---
# https://docs.ansible.com/ansible/latest/reference_appendices/general_precedence.html
# use -e 'ansible_user=root' to override the default user set in inventory vars
# on LXC root is disabled, set /etc/ssh/sshd_config 'PermitRootLogin prohibit-password'
# Cloud init images no longer need this
- name: Ensure default users exist
  hosts:
    - ubuntu
    - turingpi_cluster
  become: true
  tags:
    - init
    - ansible
  tasks:
    - name: Create Ansible Group
      ansible.builtin.group:
        name: ansible
        system: true
        state: present

    - name: Create Ansible User
      ansible.builtin.user:
        name: ansible
        group: ansible
        create_home: true
        shell: /bin/bash
        comment: Ansible automation user
        system: true
        state: present

    - name: Allow Ansible group to have passwordless sudo
      ansible.builtin.copy:
        content: "%ansible ALL=(ALL:ALL) NOPASSWD:ALL"
        dest: /etc/sudoers.d/ansible
        mode: '0440'
        validate: '/usr/sbin/visudo -cf %s'

    - name: Add SSH key for Ansible
      ansible.posix.authorized_key:
        user: ansible
        state: present
        key: 'https://github.com/akijowski.keys'

- name: Update APT packages
  hosts:
    - ubuntu
    - turingpi_cluster
  become: true
  tags:
    - init
    - packages
  tasks:
    - name: Update packages
      ansible.builtin.apt:
        upgrade: true
        update_cache: true
        autoclean: true
        autoremove: true
        cache_valid_time: 86400 # 1 day
        state: present
      register: upgrade
      retries: 30 # 5 minutes
      delay: 10
      until: upgrade is success

- name: Ensure base packages
  hosts:
    - ubuntu
    - turingpi_cluster
  become: true
  tags:
    - init
    - base
  tasks:
    - name: Update packages
      ansible.builtin.apt:
        upgrade: true
        state: present

    - name: Install base packages
      ansible.builtin.apt:
        update_cache: true
        autoclean: true
        autoremove: true
        cache_valid_time: 86400 # 1 day
        name: "{{ apt_default_packages }}"
        state: latest

- name: Ensure APT cleaned
  hosts:
    - ubuntu
    - turingpi_cluster
  become: true
  tags:
    - clean
  tasks:
    - name: Remove old packages from the cache
      ansible.builtin.apt:
        autoclean: yes

    - name: Remove dependencies that are no longer needed
      ansible.builtin.apt:
        autoremove: yes
        purge: yes

    - name: Check if a reboot is needed
      ansible.builtin.stat:
        path: /var/run/reboot-required
      register: reboot_required

    - name: Report if reboot is needed.
      ansible.builtin.debug:
        msg: Reboot required
      when: reboot_required.stat.exists

- name: Ensure Unattended Upgrades
  hosts:
    - ubuntu
    - turingpi_cluster
  become: true
  tags:
    - init
    - unattended
  tasks:
    - name: Install unattended upgrades
      ansible.builtin.import_role:
        name: hifis.unattended_upgrades
      vars:
        unattended_automatic_reboot: true
        unattended_syslog_enable: true
        unattended_email: "{{ unattended_email }}"
        unattended_mail_only_on_error: true

- name: Ensure base security applied
  hosts:
    - ubuntu
    - turingpi_cluster
  become: true
  tags:
    - init
    - security
  tasks:
    - name: Disable password authentication for root
      ansible.builtin.lineinfile:
        path: /etc/ssh/sshd_config
        state: present
        regexp: '^#?PermitRootLogin'
        line: 'PermitRootLogin prohibit-password'

    - name: UFW - Allow SSH connections
      community.general.ufw:
        rule: allow
        name: OpenSSH
      notify:
        - restart ufw

    - name: UFW - Deny all other incoming traffic by default
      community.general.ufw:
        state: enabled
        policy: deny
        direction: incoming
      notify:
        - restart ufw

  handlers:
    - name: restart ufw
      community.general.ufw:
        state: reloaded

- name: Partition Drive
  hosts:
    - ubuntu
  become: true
  tags:
    - partition
  tasks:
    - name: Ensure parted is installed
      ansible.builtin.apt:
        name:
          - parted
        state: latest

    - name: Proceed?
      ansible.builtin.pause:
        prompt: "This will completely format {{ dev_path }}! Continue? 'Y' to proceed."
      register: do_format

    - name: "Partition device {{ dev_path }}"
      community.general.parted:
        device: "{{ dev_path }}"
        number: 1
        label: gpt
        name: "{{ dev_name }}"
        fs_type: ext4
        state: present
      when: do_format.user_input == "Y"

    - name: "Format {{ dev_path }}"
      community.general.filesystem:
        dev: "{{ dev_path + '1' }}"
        fstype: ext4
        state: present
      when: do_format.user_input == "Y"

    - name: "Mount {{ dev_path }} to {{ mnt_path }}"
      ansible.posix.mount:
        src: "{{ dev_path + '1' }}"
        fstype: ext4
        path: "{{ mnt_path }}"
        state: mounted
      when: do_format.user_input == "Y"
