[project]
name = "home-server"
revision = "1.0"

# Extend configurations from subdirectories
# extends = [ "subdir1", "subdir2" ]

[profiles.default]
ANSIBLE_VAULT_PASSWORD_FILE = { description = "Ansible Vault password, will be set as a file", providers = ["vault_nixos"], as_path = true }
ANSIBLE_BECOME_PASSWORD_FILE = { description = "Ansible become password on remotes, will be set as a file", providers = ["vault_nixos"], as_path = true }
ANSIBLE_PROXMOX_TOKEN_SECRET = { description = "API Token for Ansible Proxmox access", providers = ["vault_nixos"] }

[profiles.development]
# Development profile inherits all secrets from default profile
# Only define secrets here that need different values or settings than default
# DATABASE_URL = { default = "sqlite:///dev.db" }
#
# New secrets
# REDIS_URL = { description = "Redis connection URL for caching", required = false, default = "redis://localhost:6379" }
