$ANSIBLE_VAULT;1.1;AES256
65356636313065303335386437373466353163306263633939653637363534353633393837376232
3861643232386535633562613065303636373838316562390a353364373537656562613633323064
63353739323462616530363135376238623435336461386366363733626630326165383034353865
6334653866336335350a326534623030383735626635343130626661316538656630646666386161
63343930353465313236383334366463616139303061323238303633653336313966356239356462
3735383563393933323563636337363139313437363037373162
