---
apiVersion: traefik.io/v1alpha1
kind: TraefikService
metadata:
  name: prometheus
  namespace: monitoring
  labels:
    app: prometheus
    app.kubernetes.io/name: prometheus
    app.kubernetes.io/component: network

spec:
  weighted:
    services:
      - name: prometheus-operated
        kind: Service
        port: web

---
apiVersion: traefik.io/v1alpha1
kind: TraefikService
metadata:
  name: alertmanager
  namespace: monitoring
  labels:
    app: alertmanager
    app.kubernetes.io/name: alertmanager
    app.kubernetes.io/component: network

spec:
  weighted:
    services:
      - name: alertmanager-operated
        kind: Service
        port: web

---
# Redirect to https
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: redirect-https
  namespace: monitoring
  labels:
    app.kubernetes.io/component: network
spec:
  redirectScheme:
    scheme: https
    permanent: true

---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: prometheus-tls
  namespace: monitoring
  labels:
    app: prometheus
    app.kubernetes.io/name: prometheus
    app.kubernetes.io/component: network
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`prometheus.k8s.kijowski.casa`)
      kind: Rule
      services:
        - name: prometheus
          kind: TraefikService

  tls:
    certResolver: aws-dns

---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: prometheus
  namespace: monitoring
  labels:
    app: prometheus
    app.kubernetes.io/name: prometheus
    app.kubernetes.io/component: network
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`prometheus.k8s.kijowski.casa`)
      kind: Rule
      services:
        - name: noop@internal
          kind: TraefikService
      middlewares:
        - name: redirect-https

---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: alertmanager-tls
  namespace: monitoring
  labels:
    app: alertmanager
    app.kubernetes.io/name: alertmanager
    app.kubernetes.io/component: network
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`alertmanager.k8s.kijowski.casa`)
      kind: Rule
      services:
        - name: alertmanager
          kind: TraefikService

  tls:
    certResolver: aws-dns

---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: alertmanager
  namespace: monitoring
  labels:
    app: alertmanager
    app.kubernetes.io/name: alertmanager
    app.kubernetes.io/component: network
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`alertmanager.k8s.kijowski.casa`)
      kind: Rule
      services:
        - name: noop@internal
          kind: TraefikService
      middlewares:
        - name: redirect-https
