---
- hosts: all
  name: Install Observability Tools
  become: true

  tasks:
    # https://github.com/prometheus/node_exporter
    # - name: Install Prometheus Node Exporter
    #   import_role:
    #     name: cloudalchemy.node_exporter
