---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: traefik-dashboard-custom-tls
  namespace: kube-system
  labels:
    app.kubernetes.io/name: traefik-dashboard-custom-tls
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`traefik.k8s.home.kijowski.io`) && (PathPrefix(`/dashboard`) || PathPrefix(`/api`))
      kind: Rule
      services:
        - name: api@internal
          kind: TraefikService
  tls:
    certResolver: aws-dns
