---
- name: "podman - enable arm systemd unit"
  ansible.builtin.systemd_service:
    name: "container-{{ arm_container_name}}"
    daemon_reload: true
    state: restarted
    enabled: true

- name: "podman - disable arm systemd unit"
  ansible.builtin.systemd_service:
    name: "container-{{ arm_container_name}}"
    state: stopped
