$ANSIBLE_VAULT;1.1;AES256
61373637613137643938393061353562313465376133366631376630376437356365663562323538
3435343832326432346639363030346131633736643430640a303633396132643831306365636466
30353033313238666331353766633263346531653762393033666232346265326236373366663532
3133656536353038640a333166396636613462623135626665373739613866346663313930636662
64323230393937353031646633363936373261333962393739353864356636653665393163363631
66343038333038353033626262613861373035383966313030666365643330383635653766313839
36396434656466333563363565343061346337623066366436623835383633646233316438653565
66313138356432316234373039653835366238383331393535376231386130633561313431313663
35653638336564633638613632356634663666303031366466373235383434373965646261363561
34646439353131626639643363393537623265366639303838633331663638653665626635393136
65316563366137653436643862333363343430383735333165616564376538366563353235343038
39353731346463393666323765613436393462663363383235316662663439363633663134363731
61306165376532373731363134396561633639363737333935666237323963666434356664363732
62396334373438636239323833396333646563353534653032383362656438626333393264653137
66373931316362393161336265623063663033323735303335313336663938363137353438383739
37386365646163336539303266356436623633303931376364316363316464653265376661356434
62346266663961323332373338343131343737643266353964373363383764653835646462343264
36363135643937363434363263656366656637333963383665326134343237353166383931376463
37643964656663623063376130356466633963393037336637643263633831303231386330316639
66356162366361363563
