$ANSIBLE_VAULT;1.1;AES256
38633765356365306536386265343963343935336665303232323164396364613465376136396362
6264336239303238323839663162313539643465366166620a306531366562306231613430623766
31653563666362353639343934323233336638383165633461656264383162616533326437366565
3466313738626163330a316361313232623562623061336466373739626234353462616333323430
66646562303331653066636633313661633838666337313638346239333362303365386165623037
34366532373033326465663365383461623939346333623966326665326564386636333939363530
62303763356234356161396534353230323262393163333234653336643230646262336662613037
65626363633261393137333138616132656533343530643239373263333238393738393631323034
35333561393666663233626665323762376666633365336438646433643633613238623433303132
63366331373337613665626261616265663634363631383665613638376637396533396634626435
37316333343137646466363539653932626264336337306234376434393631663239623234336437
65363030646635383033623933663535373737643133373463643730303233303962616336663763
35663937663262613237303863346132353839353065383133643236373036643234643462386136
62666339663839396332383465356130343430373431353631323939343632346631383766633163
63343463383039356664666462356432313032653236613361366534333136356332616162346633
62653936373739313862643663383632396235613861626464323662646339363837323063343834
65336636653935373037393262656632353464346434373565303130316233613662616633343664
62663239333438363037363036646538376135663231373664326438626233383035383838333433
34376566303964363438633430663532383036393666303934656432656331343430313437656461
32663936646162343334
