---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: semaphore
spec:
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      app: semaphore
  template:
    metadata:
      labels:
        app: semaphore
    spec:
      containers:
      - name: semaphore
        image: semaphoreui/semaphore:latest
        resources:
          requests:
            memory: "128Mi"
            cpu: "200m"
          limits:
            memory: "512Mi"
            cpu: "1000m"
        ports:
        - containerPort: 3000
          name: web
        envFrom:
          - configMapRef:
              name: semaphore-env-vars
        volumeMounts:
          - name: semaphore-home
            mountPath: /home/semaphore
          - name: semaphore-temp
            mountPath: /tmp/semaphore
          - name: semaphore-etc
            mountPath: /etc/semaphore
          - name: pip-reqs
            mountPath: /etc/semaphore/requirements.txt
            subPath: pip_requirements.txt
          - name: ansible-reqs
            mountPath: /home/semaphore/requirements.yml
            subPath: requirements.yml
      securityContext:
        fsGroup: 1001 # pulled from running container
      volumes:
      - name: semaphore-home
        emptyDir: {}
      - name: semaphore-temp
        emptyDir: {}
      - name: semaphore-etc
        emptyDir: {}
      - name: pip-reqs
        configMap:
          name: semaphore-pip-requirements
      - name: ansible-reqs
        configMap:
          name: semaphore-ansible-galaxy
