---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: semaphore-home
  labels:
    app.kubernetes.io/name: semaphore-home
    app.kubernetes.io/component: storage
spec:
  resources:
    requests:
      storage: 10Gi
  volumeMode: Filesystem
  storageClassName: "longhorn"
  accessModes:
    - ReadWriteOnce
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: semaphore-temp
  labels:
    app.kubernetes.io/name: semaphore-temp
    app.kubernetes.io/component: storage
spec:
  resources:
    requests:
      storage: 10Gi
  volumeMode: Filesystem
  storageClassName: "longhorn"
  accessModes:
    - ReadWriteOnce
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: semaphore-etc
  labels:
    app.kubernetes.io/name: semaphore-etc
    app.kubernetes.io/component: storage
spec:
  resources:
    requests:
      storage: 10Gi
  volumeMode: Filesystem
  storageClassName: "longhorn"
  accessModes:
    - ReadWriteOnce
