---
- name: Get binary checksum metadata
  ansible.builtin.uri:
    url: "https://github.com/coredns/coredns/releases/download/v{{ coredns_version }}/{{ coredns_tgz }}.sha256"
    return_content: true
  register: coredns_checksum_meta

- name: Get binary checksum
  ansible.builtin.set_fact:
    coredns_checksum: "{{ coredns_checksum_meta.content | split(' ') | first }}"

- name: Download binary
  ansible.builtin.get_url:
    url: "https://github.com/coredns/coredns/releases/download/v{{ coredns_version }}/{{ coredns_tgz }}"
    dest: "/tmp/coredns-{{ coredns_version }}.tgz"
    checksum: "sha256:{{ coredns_checksum }}"

- name: Install binary
  ansible.builtin.unarchive:
    src: "/tmp/coredns-{{ coredns_version }}.tgz"
    dest: "/usr/local/bin"
    remote_src: true
    keep_newer: true
    owner: "{{ coredns_system_user }}"
    group: "{{ coredns_system_group }}"
    mode: 0755
  notify: restart coredns

- name: Ensure systemd service file
  ansible.builtin.template:
    src: coredns.service.j2
    dest: /etc/systemd/system/coredns.service
    owner: root
    group: root
    mode: 0644
  notify: restart coredns
