$ANSIBLE_VAULT;1.1;AES256
64633036666639613531623734663731383638366465383736636330306336383066386636616331
3065373939663431393932646434336439653234323239620a326563643765633261343836323839
61663537653861666566636666323765376137613761383033323736356331326335363733643963
6332626338393831640a356636306638626231633830653464653662323539626432373163333832
61343839356232656331646662386138316264613237386564613565396533333933316238636237
30613838643331376438333264326466643831623264666561396536396463306536666461303638
65363233653031303339343066643933613664386566343034626161313161316130616161363765
36373363613433303666313334333332386535393862333431326161623062656461656337633537
31323161373931383132323663353231663630616362353631623339643130373735343465326166
3262303962633733643032376232623566366365366630373832
