$ANSIBLE_VAULT;1.1;AES256
31376538656565643730363138383835323734646464616230653933333237326339623764383039
3364363839663966346565643632386531643762383533320a393432373339623438653566383535
31663539323536383333376338376662363565306433393432396231303035316231393362396131
3734353939643665310a633163393631363463353962666235646136363364626361363339336334
31393132636134323138356130643737363061623934613836616537363565396363373336666434
38326434336337366664353761393636643134373764313339303831386632616533313563646638
36316234626630346561396137663563633535663137386664613436373331653639303939366164
38313235393264643230636539623863663163383732663036613665353834323963343765306537
61346233346137643038643431373330326165386436643361616335396636333138653733386530
6434616234353934393733323563633537396338653734353965
