---

# Tasks for creating the local group for Ansible.
- name: "Creating the local group for Ansible."
  ansible.builtin.group:
    name: "{{ ansible_username }}"

# Tasks for creating the sudo group.
- name: "Creating the sudo group."
  ansible.builtin.group:
    name: sudo

# Tasks for creating the local user for Ansible.
- name: "Creating the local user for Ansible."
  ansible.builtin.user:
    name: "{{ ansible_username }}"
    group: "{{ ansible_username }}"
    comment: Ansible User
    append: true
    groups: sudo
    password: '!'
    shell: /bin/bash

# Tasks for managing the authorized keys for the local users.
- name: "Managing the authorized keys for the local users."
  ansible.posix.authorized_key:
    user: "{{ item.user }}"
    state: present
    key: "{{ item.key }}"
  loop:
    - user: "{{ ansible_username }}"
      key: "{{ ansible_key }}"
  no_log: true

# Tasks for managing sudoers.d for the local users.
- name: "Managing sudoers.d for the local users."
  community.general.sudoers:
    name: "{{ item }}"
    user: "{{ item }}"
    commands: ALL
  loop:
    - "{{ ansible_username }}"
