# ssh role
create_user: adam
create_user_key: https://github.com/akijowski.keys
# apt role
sys_packages: ['curl', 'vim', 'git', 'ufw', 'fail2ban', 'gpg', 'unzip', 'mailutils']
unattended_email: 'agkijow@gmail.com'
# nfs role
nfs_mounts:
  - host: '192.168.50.95'
    source_path: '/mnt/tank00-4tb/plex/media'
    dest_path: '/opt/plex/media'
  - host: '192.168.50.95'
    source_path: '/mnt/tank00-4tb/plex/metadata'
    dest_path: '/opt/plex/metadata'
