---
all:
  children:
    molecule_consul:
      hosts:
        moleculeconsul0:
          hostname: moleculeconsul0
          proxmox_clone: ubuntu24-noble
          proxmox_clone_vmid: '8000'
          proxmox_vmid: '3002'
          proxmox_storage: vmstorage
      vars:
        proxmox_node: hyperion
