---
# https://github.com/PyratLabs/ansible-role-k3s/blob/main/documentation/README.md
k3s_cluster:
  hosts:
    kube-0:
      # additional config -> group_vars/k3s_cluster
      ansible_host: 192.168.50.7
      k3s_server:
        node-label:
          - "NodeLocation=TrueNAS"
    # kube-1:
    #   ansible_host: 192.168.50.12
    #   k3s_server:
    #     node-label:
    #       - "foo=bar"
