plex_user_name: plex
plex_group_name: plex
plex_additional_groups: []

# https://support.plex.tv/articles/202915258-where-is-the-plex-media-server-data-directory-located/
plex_metadata_basedir: /var/lib/plexmediaserver
