dns_aws_access_key_id: "{{ vault_dns_aws_access_key_id }}"
dns_aws_secret_access_key: "{{ vault_dns_aws_secret_access_key }}"
dns_record_sets:
  - record: proxmox.kijowski.casa
    value: "192.168.50.3,192.168.50.6,192.168.50.9"
  - record: hyperion.kijowski.casa
    value: "192.168.50.3"
  - record: phoebe.kijowski.casa
    value: "192.168.50.6"
  - record: mnemosyne.kijowski.casa
    value: "192.168.50.9"
  - record: truenas.kijowski.casa
    value: "192.168.50.4"
  - record: "*.k8s.kijowski.casa"
    value: "192.168.50.20"
    # For direct cluster access on the management port
  - record: "k8s.kijowski.casa"
    value: "192.168.50.20"
  - record: "*.kijowski.casa"
    value: "192.168.50.14"
  - record: "*.mgmt.k8s.kijowski.casa"
    value: "192.168.50.23"
    # For direct cluster access on the managmement port
  - record: "mgmt.k8s.kijowski.casa"
    value: "192.168.50.23"
