$ANSIBLE_VAULT;1.1;AES256
66643237656330326632353262313566333566636230636666613536353633346237363364653934
3566373366633134313164303530643839303263353138380a373964653234363734333432303937
38623064376233656565666236386661393230636632653237656231373862383765643766393436
3066613732323464350a343837323563396338396464393730656363363561346337313066653661
36313635303261626630363331643331633262616436366636323238346635326366646234356364
64616137656264643566643262333835373962343631346434356333656334303665616336323466
36376532316234373531616239636638353636343437383634393439643838626139323839653235
36356535366330303134313361363139636538343239303839663361376161353731353636656661
37613835656664653936343138613462663162343436336634396334623336633634656433623161
63643662366664336665333934653130613563623634306239396665626133373138616532663037
353730373565303331653034656238336135
