ingressClass:
  enabled: true
  isDefaultClass: true

logs:
  access:
    enabled: false

persistence:
  enabled: true

additionalArguments:
  - "--certificatesresolvers.aws-dns.acme.email=agkijow@gmail.com"
  - "--certificatesresolvers.aws-dns.acme.storage=/data/acme.json"
  - "--certificatesresolvers.aws-dns.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory"
  # - "--certificatesresolvers.aws-dns.acme.caserver=https://acme-v02.api.letsencrypt.org/directory"
  - "--certificatesresolvers.aws-dns.acme.dnschallenge=true"
  - "--certificatesresolvers.aws-dns.acme.dnschallenge.provider=route53"

env:
  - name: AWS_ACCESS_KEY_ID
    valueFrom:
      secretKeyRef:
        name: aws-creds
        key: access-key
  - name: AWS_SECRET_ACCESS_KEY
    valueFrom:
      secretKeyRef:
        name: aws-creds
        key: secret-key
