coredns_version: latest

coredns_arch_map:
  armv7l: arm
  x86_64: amd64
coredns_arch: "{{ coredns_arch_map[ansible_architecture] }}"
coredns_tgz: "coredns_{{ coredns_version }}_{{ ansible_system | lower }}_{{ coredns_arch}}.tgz"

coredns_system_user: coredns
coredns_system_group: coredns

coredns_dns_port: 5300
coredns_config_dir: /etc/coredns
coredns_zone_dir: "{{ coredns_config_dir }}/zones"

coredns_zones: {}
