---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
  destination:
    namespace: kube-system
    name: main-cluster
  project: cluster
  source:
    path: kubernetes/traefik
    repoURL: git@github.com:akijowski/home-server.git
    targetRevision: HEAD
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: whoami
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
  destination:
    namespace: whoami
    name: main-cluster
  project: cluster
  source:
    path: kubernetes/whoami
    repoURL: git@github.com:akijowski/home-server.git
    targetRevision: HEAD
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus-operator
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      # https://www.arthurkoziel.com/fixing-argocd-crd-too-long-error/
      - ServerSideApply=true
  destination:
    namespace: monitoring
    name: main-cluster
  project: cluster
  source:
    path: kubernetes/prometheus-op
    repoURL: git@github.com:akijowski/home-server.git
    targetRevision: HEAD
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
  destination:
    namespace: monitoring
    name: main-cluster
  project: cluster
  source:
    path: kubernetes/prometheus
    repoURL: git@github.com:akijowski/home-server.git
    targetRevision: HEAD
