#unattended upgrades
unattended_email: agkijow@gmail.com
# plex
plex_user_id: 1800
plex_group_id: 1800
plex_libraries_root_dir: '/var/lib/plex/libraries'
plex_metadata_nfs_root_dir: '/opt/plex/metadata'
# metadata should be local and preferably on an SSD for performance
# TODO: related support link
plex_metadata_ssd_root_dir: '/mnt/ssd/plexmetadata'
# nfs role
truenas_ipv4: '192.168.50.4'
nfs_mounts:
  - host: '{{ truenas_ipv4 }}'
    source_path: '/mnt/tank1600/plex/metadata'
    dest_path: '{{ plex_metadata_nfs_root_dir }}'

  - host: '{{ truenas_ipv4 }}'
    source_path: '/mnt/tank1600/plex/libraries/video/movies'
    dest_path: '{{ plex_libraries_root_dir }}/video/movies'
  - host: '{{ truenas_ipv4 }}'
    source_path: '/mnt/tank1600/plex/libraries/video/9round'
    dest_path: '{{ plex_libraries_root_dir }}/video/9round'
  - host: '{{ truenas_ipv4 }}'
    source_path: '/mnt/tank1600/plex/libraries/audio/music'
    dest_path: '{{ plex_libraries_root_dir }}/audio/music'

  - host: '{{ truenas_ipv4 }}'
    source_path: '/mnt/tank1600/plex/libraries/video/tv-shows'
    dest_path: '{{ plex_libraries_root_dir }}/video/tv-shows'
  - host: '{{ truenas_ipv4 }}'
    source_path: '/mnt/tank1600/plex/libraries/video/uhd-movies'
    dest_path: '{{ plex_libraries_root_dir }}/video/uhd-movies'
