---
kind: Endpoints
apiVersion: v1
metadata:
  name: proxmox-external
  namespace: external
subsets:
  - addresses:
    - ip: 192.168.11.139
    ports:
      - port: 9100
        name: metrics
---
kind: Endpoints
apiVersion: v1
metadata:
  name: plex-external
  namespace: external
subsets:
  - addresses:
    - ip: 192.168.11.5
    ports:
      - port: 9100
        name: metrics
---
apiVersion: v1
kind: Service
metadata:
  labels:
    prometheus: proxmox
  name: proxmox-external
  namespace: external
spec:
  type: ClusterIP
  ports:
  - port: 9100
    targetPort: 9100
    name: metrics
---
apiVersion: v1
kind: Service
metadata:
  labels:
    prometheus: plex
  name: plex-external
  namespace: external
spec:
  type: ClusterIP
  ports:
    - port: 9100
      targetPort: 9100
      name: metrics
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: proxmox-external
  namespace: monitoring
  labels:
    release: kube-prometheus # default selector for prometheus crd
spec:
  endpoints:
    - interval: 30s
      port: metrics
  selector:
    matchLabels:
      prometheus: proxmox
  namespaceSelector:
    matchNames:
      - external
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: plex-external
  namespace: monitoring
  labels:
    release: kube-prometheus
spec:
  endpoints:
    - interval: 30s
      port: metrics
  selector:
    matchLabels:
      prometheus: plex
  namespaceSelector:
    matchNames:
      - external
