---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: prometheus-dashboard
  namespace: monitoring
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`prometheus.home.lan`)
      kind: Rule
      services:
        - name: prometheus-k8s
          kind: Service #default
          port: web
          namespace: monitoring
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: alertmanager-dashboard
  namespace: monitoring
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`alert-manager.home.lan`)
      kind: Rule
      services:
        - name: alertmanager-main
          kind: Service #default
          port: web
          namespace: monitoring
