---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: tdarr-arm-raw-pv
  namespace: tdarr
  labels:
    app.kubernetes.io/name: tdarr-arm-raw-pv
    app.kubernetes.io/component: storage
    app.kubernetes.io/part-of: tdarr
spec:
  capacity:
    storage: 1Ti
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: /mnt/tank0400/autoripm/media
    server: 192.168.50.4

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: tdarr-cache
  namespace: tdarr
  labels:
    app.kubernetes.io/name: tdarr-cache
    app.kubernetes.io/component: storage
    app.kubernetes.io/part-of: tdarr
spec:
  capacity:
    storage: 1Ti
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: /mnt/tank0400/tdarr/cache
    server: 192.168.50.4

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: tdarr-server
  namespace: tdarr
  labels:
    app.kubernetes.io/name: tdarr-server
    app.kubernetes.io/component: storage
    app.kubernetes.io/part-of: tdarr
spec:
  capacity:
    storage: 1Ti
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: /mnt/tank0400/tdarr/server
    server: 192.168.50.4

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: plex-media-movies
  namespace: tdarr
  labels:
    app.kubernetes.io/name: plex-media-movies
    app.kubernetes.io/component: storage
    app.kubernetes.io/part-of: tdarr
spec:
  capacity:
    storage: 4Ti
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: /mnt/tank1600/plex/libraries/video/movies
    server: 192.168.50.4

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: plex-media-uhd-movies
  namespace: tdarr
  labels:
    app.kubernetes.io/name: plex-media-uhd-movies
    app.kubernetes.io/component: storage
    app.kubernetes.io/part-of: tdarr
spec:
  capacity:
    storage: 4Ti
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: /mnt/tank1600/plex/libraries/video/uhd-movies
    server: 192.168.50.4

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: plex-media-tv
  namespace: tdarr
  labels:
    app.kubernetes.io/name: plex-media-tv
    app.kubernetes.io/component: storage
    app.kubernetes.io/part-of: tdarr
spec:
  capacity:
    storage: 4Ti
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: /mnt/tank1600/plex/libraries/video/tv-shows
    server: 192.168.50.4

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: tdarr-config
  namespace: tdarr
  labels:
    app.kubernetes.io/name: tdarr-config
    app.kubernetes.io/component: storage
    app.kubernetes.io/part-of: tdarr
spec:
  capacity:
    storage: 5Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: /mnt/tank0400/tdarr/config
    server: 192.168.50.4

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tdarr-arm-raw-pvc
  namespace: tdarr
  labels:
    app.kubernetes.io/name: tdarr-arm-raw-pvc
    app.kubernetes.io/component: storage
    app.kubernetes.io/part-of: tdarr
spec:
  resources:
    requests:
      storage: 1Ti
  volumeMode: Filesystem
  storageClassName: ""
  accessModes:
    - ReadWriteMany
  volumeName: tdarr-arm-raw-pv

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tdarr-cache
  namespace: tdarr
  labels:
    app.kubernetes.io/name: tdarr-cache
    app.kubernetes.io/component: storage
    app.kubernetes.io/part-of: tdarr
spec:
  resources:
    requests:
      storage: 1Ti
  volumeMode: Filesystem
  storageClassName: ""
  accessModes:
    - ReadWriteMany
  volumeName: tdarr-cache

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tdarr-server
  namespace: tdarr
  labels:
    app.kubernetes.io/name: tdarr-server
    app.kubernetes.io/component: storage
    app.kubernetes.io/part-of: tdarr
spec:
  resources:
    requests:
      storage: 1Ti
  volumeMode: Filesystem
  storageClassName: ""
  accessModes:
    - ReadWriteMany
  volumeName: tdarr-server

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: plex-media-movies
  namespace: tdarr
  labels:
    app.kubernetes.io/name: plex-media-movies
    app.kubernetes.io/component: storage
    app.kubernetes.io/part-of: tdarr
spec:
  resources:
    requests:
      storage: 4Ti
  volumeMode: Filesystem
  storageClassName: ""
  accessModes:
    - ReadWriteMany
  volumeName: plex-media-movies

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: plex-media-uhd-movies
  namespace: tdarr
  labels:
    app.kubernetes.io/name: plex-media-uhd-movies
    app.kubernetes.io/component: storage
    app.kubernetes.io/part-of: tdarr
spec:
  resources:
    requests:
      storage: 4Ti
  volumeMode: Filesystem
  storageClassName: ""
  accessModes:
    - ReadWriteMany
  volumeName: plex-media-uhd-movies

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: plex-media-tv
  namespace: tdarr
  labels:
    app.kubernetes.io/name: plex-media-tv
    app.kubernetes.io/component: storage
    app.kubernetes.io/part-of: tdarr
spec:
  resources:
    requests:
      storage: 4Ti
  volumeMode: Filesystem
  storageClassName: ""
  accessModes:
    - ReadWriteMany
  volumeName: plex-media-tv

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tdarr-config
  namespace: tdarr
  labels:
    app.kubernetes.io/name: tdarr-config
    app.kubernetes.io/component: storage
    app.kubernetes.io/part-of: tdarr
spec:
  resources:
    requests:
      storage: 5Mi
  volumeMode: Filesystem
  storageClassName: ""
  accessModes:
    - ReadWriteMany
  volumeName: tdarr-config

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nfs-debug
  namespace: tdarr
  labels:
    app.kubernetes.io/name: nfs-debug
    app.kubernetes.io/component: storage
    app.kubernetes.io/part-of: tdarr
spec:
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: nfs-debug
  template:
    metadata:
      labels:
        app: nfs-debug
        app.kubernetes.io/name: nfs-debug
        app.kubernetes.io/component: storage
        app.kubernetes.io/part-of: tdarr
    spec:
      containers:
      - name: nfs-debug
        image: busybox
        command:
          - sh
          - -c
          - 'while true; do sleep 10; done'
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            memory: "128Mi"
            cpu: "250m"
        volumeMounts:
          - name: nfs-arm-raw
            mountPath: /opt/arm/raw
            readOnly: true
          - name: nfs-tdarr-server
            mountPath: /opt/tdarr/server
          - name: nfs-tdarr-cache
            mountPath: /opt/tdarr/cache
            readOnly: true
          - name: nfs-plex-media-movies
            mountPath: /opt/plex/libraries/movies
          - name: nfs-plex-media-uhd-movies
            mountPath: /opt/plex/libraries/uhd-movies
          - name: nfs-tdarr-config
            mountPath: /opt/tdarr/config

      volumes:
        - name: nfs-arm-raw
          persistentVolumeClaim:
            claimName: tdarr-arm-raw-pvc
        - name: nfs-tdarr-server
          persistentVolumeClaim:
            claimName: tdarr-server
        - name: nfs-tdarr-cache
          persistentVolumeClaim:
            claimName: tdarr-cache
        - name: nfs-plex-media-movies
          persistentVolumeClaim:
            claimName: plex-media-movies
        - name: nfs-plex-media-uhd-movies
          persistentVolumeClaim:
            claimName: plex-media-uhd-movies
        - name: nfs-tdarr-config
          persistentVolumeClaim:
            claimName: tdarr-config
