---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: tdarr-arm-raw-pv
  namespace: tdarr
  labels:
    app.kubernetes.io/name: tdarr-arm-raw-pv
    app.kubernetes.io/component: storage
    app.kubernetes.io/part-of: tdarr
spec:
  capacity:
    storage: 1Ti
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: /mnt/tank00-4tb/automatic-ripping-machine/raw
    server: 192.168.50.4

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tdarr-arm-raw-pvc
  namespace: tdarr
  labels:
    app.kubernetes.io/name: tdarr-arm-raw-pvc
    app.kubernetes.io/component: storage
    app.kubernetes.io/part-of: tdarr
spec:
  resources:
    requests:
      storage: 1Ti
  volumeMode: Filesystem
  storageClassName: ""
  accessModes:
    - ReadWriteMany
  volumeName: tdarr-arm-raw-pv

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nfs-debug
  namespace: tdarr
  labels:
    app.kubernetes.io/name: nfs-debug
    app.kubernetes.io/component: storage
    app.kubernetes.io/part-of: tdarr
spec:
  selector:
    matchLabels:
      app: nfs-debug
  template:
    metadata:
      labels:
        app: nfs-debug
        app.kubernetes.io/name: nfs-debug
        app.kubernetes.io/component: storage
        app.kubernetes.io/part-of: tdarr
    spec:
      containers:
      - name: nfs-debug
        image: busybox
        command:
          - sh
          - -c
          - 'while true; do sleep 10; done'
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            memory: "128Mi"
            cpu: "250m"
        volumeMounts:
          - name: nfs
            mountPath: /opt/arm/raw

      volumes:
        - name: nfs
          persistentVolumeClaim:
            claimName: tdarr-arm-raw-pvc
