---
apiVersion: traefik.io/v1alpha1
kind: TraefikService
metadata:
  name: tdarr-server
  namespace: tdarr
  labels:
    app: tdarr-server
    app.kubernetes.io/name: tdarr-server
    app.kubernetes.io/component: network
    app.kubernetes.io/part-of: tdarr

spec:
  weighted:
    services:
      - name: tdarr-server
        kind: Service
        port: web
---
# Redirect to https
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: tdarr-redirect-https
  namespace: tdarr
  labels:
    app: tdarr-server
    app.kubernetes.io/name: tdarr-server
    app.kubernetes.io/component: network
    app.kubernetes.io/part-of: tdarr
spec:
  redirectScheme:
    scheme: https
    permanent: true

---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: tdarr-server-tls
  namespace: tdarr
  labels:
    app: tdarr-server
    app.kubernetes.io/name: tdarr-server
    app.kubernetes.io/component: network
    app.kubernetes.io/part-of: tdarr
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`tdarr.k8s.home.kijowski.io`)
      kind: Rule
      services:
        - name: tdarr-server
          kind: TraefikService

  tls:
    certResolver: aws-dns

---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: tdarr-server
  namespace: tdarr
  labels:
    app: tdarr-server
    app.kubernetes.io/name: tdarr-server
    app.kubernetes.io/component: network
    app.kubernetes.io/part-of: tdarr
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`tdarr.k8s.home.kijowski.io`)
      kind: Rule
      services:
        - name: noop@internal
          kind: TraefikService
      middlewares:
        - name: tdarr-redirect-https
