---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: k8s-csi-nfs
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
  destination:
    namespace: storage
    name: main-cluster
  project: storage
  source:
    chart: csi-driver-nfs
    repoUrl: https://raw.githubusercontent.com/kubernetes-csi/csi-driver-nfs/master/charts
    targetRevision: v4.9.0
    helm:
      releaseName: csi-driver-nfs
      parameters:
        - name: "externalSnapshotter.enabled"
          value: "true"
        - name: "controller.runOnControlPlane"
          value: "true"
