proxmox_root_user: "root@pam"
proxmox_node: hyperion
lxc_description: "{{ name | capitalize }} container.  Created with Ansible"
lxc_gateway_ip: "192.168.50.1"
lxc_cores: 1
lxc_mem: 512
lxc_mem_swap: 512
lxc_disk: "vmstorage:100"
lxc_tags: "{{ ['ansible', 'ubuntu'] + [name] | list}}"
lxc_mounts: {}
lxc_features: []
lxc_unprivileged: true
lxc_os_template: nfs-iso:vztmpl/ubuntu-22.04-standard_22.04-1_amd64.tar.zst
lxc_autostart: true
