ansible_user: ansible
# I don't think this is being used any more now that I am using SSH_AUTH_SOCK to 1Password
ansible_ssh_private_key_file: /home/vscode/.ssh/github_akijowski_mbp14
ansible_python_interpreter: /usr/bin/python3
ansible_host_key_checking: False
