# truenas
truenas_host: "{{ lookup('ansible.builtin.env', 'TRUENAS_URL') }}"
truenas_api_key: "{{ lookup('ansible.builtin.env', 'TRUENAS_API_KEY') }}"
# proxmox
proxmox_host: '192.168.50.3:8006'
proxmox_root_pass: "{{ lookup('ansible.builtin.env', 'PROXMOX_ROOT_PASSWORD') }}"
