# apt role
sys_packages: ['curl', 'vim', 'git', 'ufw', 'fail2ban', 'gpg', 'unzip', 'mailutils']
unattended_email: 'agkijow@gmail.com'
# nfs role
nfs_mounts:
  - host: '192.168.50.95'
    source_path: '/mnt/tank00-4tb/automatic-ripping-machine/raw'
    dest_path: '/opt/arm/raw'
