$ANSIBLE_VAULT;1.1;AES256
35393566323639633665663564353563623235613635333665326562643433666663643438616234
6565363861356639306630316430363734323931623739380a346136303166343235643131393265
66326661656433316236346435336335356131366631343437353431396531356164663035323735
3662343135343434620a373731393334633361623434666566326331393438393932383861353666
64636132376365663538616633663432373464336633316638313262396430396564333163333037
36313064333538636265313836383561383738653333326633343632626634653639373336663735
63396230653637623062613566363938343431663962313838373464653231323830346539356361
30306130363932633433626233326636386633653832643534316664306432313534636530663537
66633263636633326461313963613631373135353964363330306137353136666438623733636331
63626165376263383435613164326139313336663932656234656464666362336465386662356561
39316462363066636135343564626232386633336630633133613333616565343330656562653330
30653538353662666130323034323531643163636662613334663133643232356161343766643562
3862
