---
- name: Configure default networking
  hosts:
    - turingpi_cluster
  debugger: on_failed
  tags:
    - net
  become: true
  tasks:
    - name: Check if cloud init is installed.
      ansible.builtin.stat:
        path: "/etc/cloud/templates/hosts.debian.tmpl"
      register: cloud_installed

# https://linuxconfig.org/netplan-network-configuration-tutorial-for-beginners
    - name: Disable cloud-init from changing network config
      ansible.builtin.copy:
        content: |
          network: {config: disabled}
        dest: /etc/cloud/cloud.cfg.d/99-disable-network-config.cfg
        owner: root
        group: root
        mode: 0644
      when: cloud_installed.stat.exists

  # to consider: https://serverfault.com/questions/1123343/how-to-handle-network-changes-and-restart-with-ansible
    - name: Configure netplan with static IP
      ansible.builtin.template:
        src: templates/netplan.yaml.j2
        dest: /etc/netplan/60-static-ip.yaml
        owner: root
        group: root
        mode: 0600
      when: cloud_installed.stat.exists
      # changed_when: true
      notify:
        - netplan apply

  handlers:
    - name: netplan apply
      ansible.builtin.command: netplan apply
      async: 45
      poll: 0
