apt_keyring_hashicorp: /etc/apt/keyrings/hashicorp.asc
apt_keyring_dir: "{{ apt_keyring_hashicorp | dirname }}"

# These are made by vault through apt install
vault_user_name: vault
vault_group_name: vault

vault_version: '1.18*'

vault_data_dir: "/opt/vault"
vault_agent_data_dir: "{{ vault_data_dir }}/vault-agent"
vault_config_dir: "/etc/vault.d"

vault_address: "127.0.0.1:8200"
# [{ansible_tmpl: "", agent_source: "", agent_dest: ""}]
vault_agent_templates: []
