ansible_user: ansible
ansible_python_interpreter: /usr/bin/python3
# K3s cluster vars
k3s_release_version: stable
k3s_become: true
# aws creds
aws_access_key_id: "{{ vault_aws_access_key_id }}" # ACMEKijowskiCasa
aws_secret_access_key: "{{ vault_aws_secret_access_key }}"
