$ANSIBLE_VAULT;1.1;AES256
66376366336630666166633932636533623534336466663736613864343733613363623833393539
6236613235336434396434313862633336343362633061370a353439623233333739666439306664
34393035383635356436316239303938356434303765363930373136303933643230653365303966
3033353030616132330a383336616261396432323131653464666632323134336534663064383863
30303631363436313264323962323562313939356265303464393063636162663037303964313530
30376365393830333266666230346262373834656164393538383234653861336462323139313033
37663665663338343461653664633733323762366561633262396330396138356666346132346338
66346236353563666361636230396534663634303033346133623933653632343736373333626564
35353662353330373335633163353436333961363462323064323136316438353331653335663364
34366166646232656235333334336637306664316533343432313331313637623535623335326233
31393935336138316336663232663031636239323364646362316138346161623261373230313965
33626236313136356133343865626438646138373461663430366438633630373663316335313332
66633961363066656263356538336663613430363264376262316532346636616163
