---
roles:
  - name: hifis.unattended_upgrades
  # - name: cloudalchemy.coredns
  - name: xanmanning.k3s
  # - name: geerlingguy.docker
  # - name: cloudalchemy.node_exporter

collections:
  - name: ansible.posix
  - name: ansible.utils
  - name: community.general
  - name: community.crypto
  - name: amazon.aws
  - name: https://github.com/evrardjp/ansible-collection-ha.git # keepalived and haproxy
    type: git
    version: main
  # - name: vladgh.samba
