---
roles:
  - name: hifis.unattended_upgrades
  # - name: cloudalchemy.node_exporter

collections:
  - name: ansible.posix
  - name: ansible.utils
  - name: community.general
  - name: community.crypto
