# These are intended as default secret variables for playbooks.
# If a playbook has a variable that matches one of these keys and this file is passed with --extra-vars, it will be used.

truenas_api_key: 'really-long-api-key'
proxmox_root_pass: 'super-good-root-password'
container_pass: 'pretty-good-password'
