apt_keyring_hashicorp: /etc/apt/keyrings/hashicorp.asc
apt_keyring_dir: "{{ apt_keyring_hashicorp | dirname }}"

consul_user_name: consul
consul_group_name: consul

# false for client mode
consul_agent_server: true
# set to true to enable bootstrap mode
consul_agent_server_bootstrap: false

consul_config_dir: "/etc/consul.d"
consul_data_dir: "/opt/consul/data"
consul_tls_dir: "/opt/consul/tls"
