---
all:
  children:
    molecule_consul:
      hosts:
        moleculeconsul0:
          # Workaround to broken proxmox inventory
          ansible_host: moleculeconsul0.lab.arpa
          hostname: moleculeconsul0.lab.arpa
          proxmox_clone: debian13-trixie-multi-packer
          proxmox_clone_vmid: '9001'
          proxmox_vmid: '3002'
          proxmox_storage: vmstorage
      vars:
        proxmox_node: hyperion
