---
plugin: community.proxmox.proxmox

user: "{{ lookup('ansible.builtin.env', 'ANSIBLE_PROXMOX_USER') }}"
token_id: "{{ lookup('ansible.builtin.env', 'ANSIBLE_PROXMOX_TOKEN_ID') }}"
token_secret: "{{ lookup('ansible.builtin.env', 'ANSIBLE_PROXMOX_TOKEN_SECRET') }}"

validate_certs: true
want_facts: true

exclude_nodes: true

keyed_groups:
  - key: proxmox_tags_parsed
    separator: "_"
    prefix: group
# By default the hosts will show up as tags_<name> so host vars go under the name, but we can rename with groups so group vars make sense
groups:
  molecule_consul: "'consul' in (proxmox_tags_parsed|list)"

# Return only running VMs/LXCs that are tagged as 'molecule'
filters:
  - proxmox_status == "running"
  - "proxmox_tags_parsed is defined and 'molecule' in proxmox_tags_parsed"

want_proxmox_nodes_ansible_host: true
compose:
  # default to lxc IP otherwise assume qemu
  #
  # Apparently with the latest Ansible, these values are being marked as "unsafe" (__ansible_unsafe) preventing use in jinja templates
  # workaround is to statically add the ansible_host value for now to the static inventory
  #
  ansible_host: "proxmox_agent_interfaces[1].get('ip-addresses')[0]"
  #ansible_host: proxmox_lxc_interfaces[1]["inet"] | default(proxmox_agent_interfaces[1]["ip-addresses"][0] | default(proxmox_net0.ip)) | ansible.utils.ipaddr('address')
  #ansible_host: proxmox_ipconfig0.ip | default(proxmox_net0.ip) | ansible.utils.ipaddr('address')
  # use the qemu guest agent IP. First one is localhost, so use the second one.
  # workaround for the inconsistent naming: https://github.com/ansible-collections/community.general/issues/4854#issuecomment-1295908101
  qemu_ipv4: proxmox_agent_interfaces[1]["ip-addresses"][0] | default(proxmox_net0.ip) | ansible.utils.ipaddr('address')
  # use the lxc interfaces. First one is localhost, so use the second one.
  lxc_ipv4: proxmox_lxc_interfaces[1]["inet"] | ansible.utils.ipaddr('address')
