---
apiVersion: traefik.io/v1alpha1
kind: TraefikService
metadata:
  name: longhorn
spec:
  weighted:
    services:
      - name: longhorn-frontend
        kind: Service
        port: http
---
# Redirect to https
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: longhorn-redirect-https
spec:
  redirectScheme:
    scheme: https
    permanent: true
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: longhorn-tls
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`longhorn.mgmt.k8s.kijowski.casa`)
      priority: 10
      kind: Rule
      services:
        - name: longhorn
          kind: TraefikService

  tls:
    certResolver: aws-dns

---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: longhorn
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`longhorn.mgmt.k8s.kijowski.casa`)
      kind: Rule
      services:
        - name: noop@internal
          kind: TraefikService
      middlewares:
        - name: longhorn-redirect-https
