---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tdarr
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
  destination:
    namespace: tdarr
    name: main-cluster
  project: cluster
  source:
    path: kubernetes/tdarr
    repoURL: git@github.com:akijowski/home-server.git
    targetRevision: HEAD
