apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: whoami

commonLabels:
  app: whoami
  app.kubernetes.io/part-of: whoami

resources:
  - base/deploy.yaml
  - base/traefik.yaml

replicas:
  - name: whoami
    count: 1

images:
  - name: traefik/whoami:latest
    newTag: latest
