---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: tdarr-arm-raw-pv
  labels:
    app.kubernetes.io/name: tdarr-arm-raw-pv
spec:
  capacity:
    storage: 1Ti
  nfs:
    path: /mnt/tank1600/autoripm/media

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: tdarr-cache
  labels:
    app.kubernetes.io/name: tdarr-cache
spec:
  capacity:
    storage: 1Ti
  nfs:
    path: /mnt/tank0400/tdarr/cache

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: tdarr-server
  labels:
    app.kubernetes.io/name: tdarr-server
spec:
  capacity:
    storage: 1Ti
  nfs:
    path: /mnt/tank0400/tdarr/server

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: plex-media-movies
  labels:
    app.kubernetes.io/name: plex-media-movies
spec:
  capacity:
    storage: 4Ti
  nfs:
    path: /mnt/tank1600/plex/libraries/video/movies

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: plex-media-uhd-movies
  labels:
    app.kubernetes.io/name: plex-media-uhd-movies
spec:
  capacity:
    storage: 4Ti
  nfs:
    path: /mnt/tank1600/plex/libraries/video/uhd-movies

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: plex-media-tv
  labels:
    app.kubernetes.io/name: plex-media-tv
spec:
  capacity:
    storage: 4Ti
  nfs:
    path: /mnt/tank1600/plex/libraries/video/tv-shows

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: tdarr-config
  labels:
    app.kubernetes.io/name: tdarr-config
spec:
  capacity:
    storage: 5Mi
  nfs:
    path: /mnt/tank0400/tdarr/config

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tdarr-arm-raw-pvc
  labels:
    app.kubernetes.io/name: tdarr-arm-raw-pvc
spec:
  resources:
    requests:
      storage: 1Ti
  volumeName: tdarr-arm-raw-pv

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tdarr-cache
  labels:
    app.kubernetes.io/name: tdarr-cache
spec:
  resources:
    requests:
      storage: 1Ti
  volumeName: tdarr-cache

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tdarr-server
  labels:
    app.kubernetes.io/name: tdarr-server
spec:
  resources:
    requests:
      storage: 1Ti
  volumeName: tdarr-server

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: plex-media-movies
  labels:
    app.kubernetes.io/name: plex-media-movies
spec:
  resources:
    requests:
      storage: 4Ti
  volumeName: plex-media-movies

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: plex-media-uhd-movies
  labels:
    app.kubernetes.io/name: plex-media-uhd-movies
spec:
  resources:
    requests:
      storage: 4Ti
  volumeName: plex-media-uhd-movies

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: plex-media-tv
  labels:
    app.kubernetes.io/name: plex-media-tv
spec:
  resources:
    requests:
      storage: 4Ti
  volumeName: plex-media-tv

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tdarr-config
  labels:
    app.kubernetes.io/name: tdarr-config
spec:
  resources:
    requests:
      storage: 5Mi
  volumeName: tdarr-config

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nfs-debug
  labels:
    app.kubernetes.io/name: nfs-debug
    app.kubernetes.io/component: storage
spec:
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: nfs-debug
  template:
    metadata:
      labels:
        app: nfs-debug
        app.kubernetes.io/name: nfs-debug
        app.kubernetes.io/component: storage
        app.kubernetes.io/part-of: tdarr
    spec:
      containers:
      - name: nfs-debug
        image: busybox
        command:
          - sh
          - -c
          - 'while true; do sleep 10; done'
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            memory: "128Mi"
            cpu: "250m"
        volumeMounts:
          - name: nfs-arm-raw
            mountPath: /opt/arm/raw
            readOnly: true
          - name: nfs-tdarr-server
            mountPath: /opt/tdarr/server
          - name: nfs-tdarr-cache
            mountPath: /opt/tdarr/cache
            readOnly: true
          - name: nfs-plex-media-movies
            mountPath: /opt/plex/libraries/movies
          - name: nfs-plex-media-uhd-movies
            mountPath: /opt/plex/libraries/uhd-movies
          - name: nfs-tdarr-config
            mountPath: /opt/tdarr/config

      volumes:
        - name: nfs-arm-raw
          persistentVolumeClaim:
            claimName: tdarr-arm-raw-pvc
        - name: nfs-tdarr-server
          persistentVolumeClaim:
            claimName: tdarr-server
        - name: nfs-tdarr-cache
          persistentVolumeClaim:
            claimName: tdarr-cache
        - name: nfs-plex-media-movies
          persistentVolumeClaim:
            claimName: plex-media-movies
        - name: nfs-plex-media-uhd-movies
          persistentVolumeClaim:
            claimName: plex-media-uhd-movies
        - name: nfs-tdarr-config
          persistentVolumeClaim:
            claimName: tdarr-config
