---
apiVersion: v1
kind: Service
metadata:
  name: tdarr-node
  labels:
    app: tdarr-node
    app.kubernetes.io/name: tdarr-node
    app.kubernetes.io/component: node
spec:
  selector:
    app: tdarr-node
  clusterIP: None
  ports:
    - name: node
      port: 8266

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: tdarr-node
  labels:
    app: tdarr-node
    app.kubernetes.io/name: tdarr-node
    app.kubernetes.io/component: node
spec:
  serviceName: tdarr-node
  replicas: 1
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      app: tdarr-node
  template:
    metadata:
      labels:
        app: tdarr-node # used for affinity
        app.kubernetes.io/name: tdarr-node
        app.kubernetes.io/component: node
    spec:
      containers:
        - name: tdarr-node
          image: ghcr.io/haveagitgat/tdarr_node:2.27.02
          imagePullPolicy: Always
          resources:
            limits:
              memory: "4Gi"
              cpu: "6"
          ports:
            - containerPort: 8266
              name: node
          env:
            - name: nodeName
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          envFrom:
            - configMapRef:
                name: tdarr-node-env
          volumeMounts:
            - name: config
              mountPath: /app/configs
            - name: logs
              mountPath: /app/logs
            - name: nfs-raw-media
              mountPath: /media
            - name: nfs-cache
              mountPath: /temp
            - name: nfs-plex-media-movies
              mountPath: /opt/plex/libraries/movies
            - name: nfs-plex-media-uhd-movies
              mountPath: /opt/plex/libraries/uhd-movies
            - name: nfs-plex-media-tv
              mountPath: /opt/plex/libraries/tv-shows
      restartPolicy: Always

      volumes:
        - name: logs
          emptyDir: {}
        - name: config
          emptyDir: {}

        - name: nfs-cache
          persistentVolumeClaim:
            claimName: tdarr-cache
        - name: nfs-raw-media
          persistentVolumeClaim:
            claimName: tdarr-arm-raw-pvc
        - name: nfs-server
          persistentVolumeClaim:
            claimName: tdarr-server
        - name: nfs-config
          persistentVolumeClaim:
            claimName: tdarr-config
        - name: nfs-plex-media-movies
          persistentVolumeClaim:
            claimName: plex-media-movies
        - name: nfs-plex-media-uhd-movies
          persistentVolumeClaim:
            claimName: plex-media-uhd-movies
        - name: nfs-plex-media-tv
          persistentVolumeClaim:
            claimName: plex-media-tv

      # Require the node on an agent node when scheduling
      # Prevent tdarr from being scheduled on the same node
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: 'node-role.kubernetes.io/control-plane'
                    operator: DoesNotExist
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - tdarr-node
              topologyKey: "kubernetes.io/hostname"

      # Any filesystem mounted to the pod will be owned by this group
      securityContext:
        fsGroup: 1400

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: tdarr-node-env
  labels:
    app: tdarr-node
    app.kubernetes.io/name: tdarr-node-env
    app.kubernetes.io/component: config
data:
  TZ: "America/Denver"
  PUID: "1400"
  PGID: "1400"
  serverIP: "tdarr-server.tdarr"
  serverPort: "8266"
  internalNode: "false"
  inContainer: "true"
  ffmpegVersion: "6"
  logLevel: "DEBUG"
