apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - app-projects/project-cluster.yaml
  - app-projects/project-mgmt.yaml
  - app-projects/project-monitoring.yaml
  - resources/apps-mgmt
  - resources/apps-main
