apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - app-projects/project-cluster.yaml
  - app-projects/project-database.yaml
  - app-projects/project-mgmt.yaml
  - app-projects/project-monitoring.yaml
  - app-projects/project-storage.yaml
  - resources/apps-database
  - resources/apps-mgmt
  - resources/apps-main
  - resources/apps-monitoring
  - resources/apps-storage
