apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: monitoring-crds

resources:
  - https://raw.githubusercontent.com/prometheus-operator/prometheus-operator/v0.78.2/bundle.yaml
  - https://github.com/grafana/grafana-operator/releases/download/v5.15.1/kustomize-cluster_scoped.yaml

# Add node selectors to keep the operator on the control-plane node
patches:
  - target:
      kind: Deployment
      name: prometheus-operator
    patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: prometheus-operator
      spec:
        template:
          spec:
            nodeSelector:
              kubernetes.io/os: linux
              node-role.kubernetes.io/control-plane: "true"

  # https://github.com/kubernetes-sigs/kustomize/issues/1593#issuecomment-1470553193
  # Delete the namespace, argo will make it for us
  - target:
      kind: Namespace
    patch: |-
      $patch: delete
      apiVersion: v1
      kind: Namespace
      metadata:
        name: monitoring-crds
