---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: semaphore
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
  destination:
    namespace: semaphore
    server: https://kubernetes.default.svc
  project: mgmt
  source:
    path: kubernetes/semaphore
    repoURL: git@github.com:akijowski/home-server.git
    targetRevision: HEAD
