---

- name: Ensure system state
  import_tasks: ensure.yml
  become: true
  tags:
    - arm_ensure

- name: Install ARM
  import_tasks: install_docker.yml
  become: true
  tags:
    - arm_install
  when: use_docker

- name: Install ARM
  import_tasks: install_podman.yml
  become: true
  tags:
    - arm_install
  when: not use_docker
