---
- name: Restart UFW service
  become: true
  community.general.ufw:
    state: reloaded

- name: Restart plexmediaserver service
  become: true
  ansible.builtin.systemd:
    daemon_reload: true
    name: plexmediaserver
    state: restarted
